/**
 * @module codegen
 *
 * Code generation utilities for the LocalTarget compiler.
 *
 * Generates runnable TypeScript source files that wire up agents using
 * the Vercel AI SDK. All generated code targets Node.js with ESM modules
 * and is intended to be executed via `tsx`.
 */

import type { AgentAssembly, AgentResource } from './types.js';

// ─── Provider Mapping ───────────────────────────────────────────────────────

/**
 * Maps a model provider name (as declared in the assembly) to its
 * corresponding Vercel AI SDK package and factory function.
 */
const PROVIDER_MAP: Record<string, { pkg: string; factory: string }> = {
  anthropic: { pkg: '@ai-sdk/anthropic', factory: 'anthropic' },
  openai: { pkg: '@ai-sdk/openai', factory: 'openai' },
  google: { pkg: '@ai-sdk/google', factory: 'google' },
};

// ─── Helpers ────────────────────────────────────────────────────────────────

/**
 * Sanitize a resource display name into a valid JS identifier.
 */
function toIdentifier(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_$]/g, '_')
    .replace(/^(\d)/, '_$1');
}

/**
 * Find resources of a given type in the assembly.
 */
function findResources(assembly: AgentAssembly, type: string): AgentResource[] {
  return Object.values(assembly.resources).filter(r => r.type === type);
}

// ─── Agent Module Generation ────────────────────────────────────────────────

/**
 * Generate a TypeScript module for a single agent.
 *
 * The generated module exports a `chat()` function that accepts a user
 * message and returns the assistant's response. It uses Vercel AI SDK's
 * `generateText` to invoke the configured model with tools and a system
 * prompt.
 *
 * @param agentResource  - The Agent resource from the assembly.
 * @param modelResource  - The Model resource bound to this agent (may be undefined).
 * @param toolResources  - Tool resources bound to this agent.
 * @param promptResource - The Prompt resource bound to this agent (may be undefined).
 * @param mcpResources   - MCP Server resources bound to this agent.
 * @param assembly       - The full Agent Assembly (for cross-references).
 * @returns Generated TypeScript source code as a string.
 */
export function generateAgentModule(
  agentResource: AgentResource,
  modelResource: AgentResource | undefined,
  toolResources: AgentResource[],
  promptResource: AgentResource | undefined,
  mcpResources: AgentResource[],
  assembly: AgentAssembly,
): string {
  const agentName = agentResource.displayName;
  const props = agentResource.properties as Record<string, unknown>;

  // Resolve model provider and model ID.
  const provider = (modelResource?.properties as Record<string, unknown>)?.provider as string | undefined ?? 'anthropic';
  const modelId = (modelResource?.properties as Record<string, unknown>)?.modelId as string | undefined ?? 'claude-sonnet-4';
  const providerInfo = PROVIDER_MAP[provider] ?? PROVIDER_MAP['anthropic']!;

  // Resolve system prompt.
  const systemPrompt = resolveSystemPrompt(props, promptResource);

  // Build imports.
  const imports: string[] = [
    `import { generateText } from 'ai';`,
    `import { ${providerInfo.factory} } from '${providerInfo.pkg}';`,
  ];

  if (mcpResources.length > 0) {
    imports.push(`import { Client } from '@modelcontextprotocol/sdk/client/index.js';`);
    imports.push(`import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';`);
  }

  // Build tool definitions.
  const toolsCode = generateToolDefinitions(toolResources, assembly);

  // Build MCP setup code.
  const mcpSetup = mcpResources.length > 0
    ? generateMCPSetup(mcpResources)
    : '';

  // Build conversation history type.
  const code = `${imports.join('\n')}

/**
 * Agent: ${agentName}
 * Generated by @agentforge/target-local
 */

type Message = { role: 'user' | 'assistant'; content: string };

const conversationHistory: Message[] = [];

const SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)};

${mcpSetup}
${toolsCode}

/**
 * Send a message to the ${agentName} agent and receive a response.
 *
 * @param userMessage - The user's input message.
 * @returns The assistant's response text.
 */
export async function chat(userMessage: string): Promise<string> {${mcpResources.length > 0 ? '\n  await initMCPClients();' : ''}

  conversationHistory.push({ role: 'user', content: userMessage });

  const result = await generateText({
    model: ${providerInfo.factory}('${modelId}'),
    system: SYSTEM_PROMPT,
    messages: conversationHistory,${toolsCode.trim() ? `\n    tools: agentTools,\n    maxSteps: 10,` : ''}
  });

  const assistantMessage = result.text;
  conversationHistory.push({ role: 'assistant', content: assistantMessage });

  return assistantMessage;
}

/**
 * Reset the conversation history for this agent.
 */
export function resetConversation(): void {
  conversationHistory.length = 0;
}

/**
 * Get the agent's display name.
 */
export const agentName = ${JSON.stringify(agentName)};
`;

  return code;
}

// ─── System Prompt Resolution ───────────────────────────────────────────────

/**
 * Resolve the system prompt from agent properties or a bound Prompt resource.
 */
function resolveSystemPrompt(
  agentProps: Record<string, unknown>,
  promptResource: AgentResource | undefined,
): string {
  // Prefer explicit prompt from the Prompt resource.
  if (promptResource) {
    const promptProps = promptResource.properties as Record<string, unknown>;
    if (typeof promptProps['content'] === 'string') {
      return promptProps['content'];
    }
    if (typeof promptProps['template'] === 'string') {
      return promptProps['template'];
    }
  }

  // Fall back to the agent's own prompt/systemPrompt property.
  if (typeof agentProps['systemPrompt'] === 'string') {
    return agentProps['systemPrompt'];
  }
  if (typeof agentProps['prompt'] === 'string') {
    return agentProps['prompt'];
  }

  return 'You are a helpful assistant.';
}

// ─── Tool Definition Generation ─────────────────────────────────────────────

/**
 * Generate the `agentTools` object definition for Vercel AI SDK `tools` param.
 */
function generateToolDefinitions(
  toolResources: AgentResource[],
  assembly: AgentAssembly,
): string {
  if (toolResources.length === 0) return '';

  const imports = [`import { z } from 'zod';`, `import { tool } from 'ai';`];
  const toolEntries: string[] = [];

  for (const toolRes of toolResources) {
    const props = toolRes.properties as Record<string, unknown>;
    const toolName = toIdentifier(toolRes.displayName);
    const description = (props['description'] as string) ?? `Tool: ${toolRes.displayName}`;
    const parameters = props['parameters'] as Record<string, unknown> | undefined;
    const handlerType = (props['handlerType'] as string) ?? 'inline';

    // Generate Zod schema from parameter definitions.
    const zodSchema = generateZodSchema(parameters);

    // Generate the execute function based on handler type.
    const executeBody = generateToolExecute(toolRes, handlerType, assembly);

    toolEntries.push(`  ${toolName}: tool({
    description: ${JSON.stringify(description)},
    parameters: ${zodSchema},
    execute: async (${parameters ? 'params' : ''}) => {
${executeBody}
    },
  })`);
  }

  return `
${imports.join('\n')}

const agentTools = {
${toolEntries.join(',\n')},
};
`;
}

/**
 * Generate a Zod schema from a parameter definition object.
 *
 * The parameter definition follows a simplified JSON Schema-like structure:
 * `{ paramName: { type: 'string', description: '...' } }`
 */
function generateZodSchema(parameters: Record<string, unknown> | undefined): string {
  if (!parameters || Object.keys(parameters).length === 0) {
    return 'z.object({})';
  }

  const fields: string[] = [];
  for (const [key, def] of Object.entries(parameters)) {
    const paramDef = def as Record<string, unknown>;
    const type = (paramDef['type'] as string) ?? 'string';
    const description = paramDef['description'] as string | undefined;

    let zodType: string;
    switch (type) {
      case 'number':
      case 'integer':
        zodType = 'z.number()';
        break;
      case 'boolean':
        zodType = 'z.boolean()';
        break;
      case 'array':
        zodType = 'z.array(z.unknown())';
        break;
      case 'object':
        zodType = 'z.object({}).passthrough()';
        break;
      default:
        zodType = 'z.string()';
    }

    if (description) {
      zodType += `.describe(${JSON.stringify(description)})`;
    }

    if (paramDef['optional'] === true || paramDef['required'] === false) {
      zodType += '.optional()';
    }

    fields.push(`    ${key}: ${zodType}`);
  }

  return `z.object({\n${fields.join(',\n')},\n  })`;
}

/**
 * Generate the body of a tool's execute function.
 */
function generateToolExecute(
  toolRes: AgentResource,
  handlerType: string,
  _assembly: AgentAssembly,
): string {
  const props = toolRes.properties as Record<string, unknown>;

  switch (handlerType) {
    case 'file': {
      // File-referenced handler — import and call the handler function.
      const handlerPath = (props['handlerFile'] as string) ?? (props['handler'] as string);
      if (handlerPath) {
        // Asset will be copied to tools/ directory.
        const assetPath = `./tools/${handlerPath.split('/').pop()}`;
        return `      const handler = await import('${assetPath}');\n      return handler.default(params);`;
      }
      return `      throw new Error('Tool handler file not configured');`;
    }

    case 'mcp': {
      // MCP tool — delegate to the MCP client.
      const mcpToolName = (props['mcpToolName'] as string) ?? toolRes.displayName;
      const serverId = (props['mcpServerId'] as string) ?? '';
      const clientVar = toIdentifier(serverId || 'default') + 'Client';
      return `      const result = await ${clientVar}.callTool({ name: ${JSON.stringify(mcpToolName)}, arguments: params });\n      return result.content;`;
    }

    case 'inline':
    default: {
      // Inline handler — the handler code is embedded in the assembly.
      const handlerCode = props['handlerCode'] as string | undefined;
      if (handlerCode) {
        return `      ${handlerCode}`;
      }
      // If inline but no code, check for asset reference.
      if (toolRes.assetRefs.length > 0) {
        const assetRef = toolRes.assetRefs[0]!;
        const assetPath = `./tools/${assetRef.assemblyPath.split('/').pop()}`;
        return `      const handler = await import('${assetPath}');\n      return handler.default(params);`;
      }
      return `      throw new Error('Tool handler not implemented: ${toolRes.displayName}');`;
    }
  }
}

// ─── MCP Setup Generation ───────────────────────────────────────────────────

/**
 * Generate code that spawns MCP server processes and creates clients.
 *
 * For each MCPServer resource, the generated code:
 * 1. Creates a StdioClientTransport that spawns the server process
 * 2. Creates an MCP Client and connects to the transport
 * 3. Lists available tools from the server
 *
 * @param mcpResources - MCP Server resources from the assembly.
 * @returns Generated TypeScript code for MCP client setup.
 */
export function generateMCPSetup(mcpResources: AgentResource[]): string {
  if (mcpResources.length === 0) return '';

  const declarations: string[] = [];
  const initSteps: string[] = [];

  for (const mcpRes of mcpResources) {
    const props = mcpRes.properties as Record<string, unknown>;
    const serverName = mcpRes.displayName;
    const clientVar = toIdentifier(serverName) + 'Client';
    const command = (props['command'] as string) ?? 'npx';
    const args = (props['args'] as string[]) ?? [];
    const env = (props['env'] as Record<string, string>) ?? {};

    declarations.push(`let ${clientVar}: Client;`);

    const envEntries = Object.entries(env)
      .map(([k, v]) => `      ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
      .join(',\n');

    const envBlock = Object.keys(env).length > 0
      ? `,\n    env: {\n      ...process.env as Record<string, string>,\n${envEntries},\n    }`
      : '';

    initSteps.push(`  // Initialize MCP server: ${serverName}
  const ${clientVar}Transport = new StdioClientTransport({
    command: ${JSON.stringify(command)},
    args: ${JSON.stringify(args)}${envBlock},
  });

  ${clientVar} = new Client(
    { name: ${JSON.stringify(serverName + '-client')}, version: '1.0.0' },
    { capabilities: {} },
  );

  await ${clientVar}.connect(${clientVar}Transport);
  const ${clientVar}Tools = await ${clientVar}.listTools();
  console.log('[MCP] Connected to ${serverName}:', ${clientVar}Tools.tools.map(t => t.name).join(', '));`);
  }

  return `
${declarations.join('\n')}
let mcpInitialized = false;

async function initMCPClients(): Promise<void> {
  if (mcpInitialized) return;
  mcpInitialized = true;

${initSteps.join('\n\n')}
}
`;
}

// ─── Runtime Generation ─────────────────────────────────────────────────────

/**
 * Generate the main runtime entrypoint (`runtime.ts`).
 *
 * If a single agent is defined, the runtime starts an interactive CLI chat
 * session with that agent. If multiple agents are defined, it presents a
 * selection menu first.
 *
 * @param agents - Array of agent display names (matching generated module filenames).
 * @returns Generated TypeScript source code for the runtime entrypoint.
 */
export function generateRuntime(agents: string[]): string {
  const importStatements = agents.map(name => {
    const id = toIdentifier(name);
    return `import * as ${id}Agent from './agents/${name}.js';`;
  });

  if (agents.length === 0) {
    return `console.error('No agents configured. Please define at least one Agent resource.');
process.exit(1);
`;
  }

  if (agents.length === 1) {
    const name = agents[0]!;
    const id = toIdentifier(name);
    return `${importStatements[0]}
import * as readline from 'node:readline';

/**
 * AgentForge Local Runtime
 * Agent: ${name}
 * Generated by @agentforge/target-local
 */

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function prompt(): void {
  rl.question('You: ', async (input: string) => {
    const trimmed = input.trim();

    if (trimmed === '' || trimmed === '/quit' || trimmed === '/exit') {
      console.log('Goodbye!');
      rl.close();
      process.exit(0);
    }

    if (trimmed === '/reset') {
      ${id}Agent.resetConversation();
      console.log('Conversation reset.');
      prompt();
      return;
    }

    try {
      const response = await ${id}Agent.chat(trimmed);
      console.log(\`\\nAssistant: \${response}\\n\`);
    } catch (error) {
      console.error('Error:', error instanceof Error ? error.message : error);
    }

    prompt();
  });
}

console.log(\`\\n--- AgentForge Local Runtime ---\`);
console.log(\`Agent: ${name}\`);
console.log(\`Commands: /reset (clear history), /quit (exit)\\n\`);

prompt();
`;
  }

  // Multiple agents — present selection menu.
  const agentImports = importStatements.join('\n');
  const agentMap = agents.map(name => {
    const id = toIdentifier(name);
    return `  '${name}': ${id}Agent`;
  }).join(',\n');

  return `${agentImports}
import * as readline from 'node:readline';

/**
 * AgentForge Local Runtime
 * Multiple agents available
 * Generated by @agentforge/target-local
 */

const agents: Record<string, { chat: (msg: string) => Promise<string>; resetConversation: () => void; agentName: string }> = {
${agentMap},
};

const agentNames = Object.keys(agents);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

let currentAgent: string | null = null;

function showMenu(): void {
  console.log('\\nAvailable agents:');
  agentNames.forEach((name, i) => {
    console.log(\`  \${i + 1}. \${name}\`);
  });
  console.log();

  rl.question('Select an agent (number or name): ', (input: string) => {
    const trimmed = input.trim();
    const num = parseInt(trimmed, 10);

    if (num >= 1 && num <= agentNames.length) {
      currentAgent = agentNames[num - 1]!;
    } else if (agentNames.includes(trimmed)) {
      currentAgent = trimmed;
    } else {
      console.log('Invalid selection.');
      showMenu();
      return;
    }

    console.log(\`\\nChatting with: \${currentAgent}\`);
    console.log('Commands: /switch (change agent), /reset (clear history), /quit (exit)\\n');
    prompt();
  });
}

function prompt(): void {
  rl.question('You: ', async (input: string) => {
    const trimmed = input.trim();

    if (trimmed === '' || trimmed === '/quit' || trimmed === '/exit') {
      console.log('Goodbye!');
      rl.close();
      process.exit(0);
    }

    if (trimmed === '/switch') {
      currentAgent = null;
      showMenu();
      return;
    }

    if (trimmed === '/reset') {
      agents[currentAgent!]!.resetConversation();
      console.log('Conversation reset.');
      prompt();
      return;
    }

    try {
      const response = await agents[currentAgent!]!.chat(trimmed);
      console.log(\`\\nAssistant: \${response}\\n\`);
    } catch (error) {
      console.error('Error:', error instanceof Error ? error.message : error);
    }

    prompt();
  });
}

console.log('\\n--- AgentForge Local Runtime ---');
console.log(\`\${agentNames.length} agent(s) available\\n\`);

showMenu();
`;
}

// ─── Package.json Generation ────────────────────────────────────────────────

/**
 * Generate the `package.json` for the compiled runtime project.
 *
 * Includes Vercel AI SDK, provider packages for all models referenced in
 * the assembly, and MCP SDK if any MCP servers are present.
 *
 * @param assembly - The Agent Assembly to derive dependencies from.
 * @returns A plain object suitable for JSON serialization as package.json.
 */
export function generatePackageJson(assembly: AgentAssembly): Record<string, unknown> {
  const modelResources = findResources(assembly, 'agentforge::core::Model');
  const mcpResources = findResources(assembly, 'agentforge::core::MCPServer');
  const toolResources = findResources(assembly, 'agentforge::core::Tool');

  // Determine which provider packages are needed.
  const providers = new Set<string>();
  for (const model of modelResources) {
    const provider = (model.properties as Record<string, unknown>)['provider'] as string | undefined;
    if (provider && PROVIDER_MAP[provider]) {
      providers.add(provider);
    }
  }

  // If no models specified, default to anthropic.
  if (providers.size === 0) {
    providers.add('anthropic');
  }

  // Build dependencies.
  const deps: Record<string, string> = {
    'ai': '^4.0.0',
    'zod': '^3.23.0',
  };

  for (const provider of providers) {
    const info = PROVIDER_MAP[provider];
    if (info) {
      deps[info.pkg] = '^1.0.0';
    }
  }

  if (mcpResources.length > 0) {
    deps['@modelcontextprotocol/sdk'] = '^1.0.0';
  }

  return {
    name: `agentforge-runtime-${assembly.metadata.stackName.toLowerCase().replace(/[^a-z0-9-]/g, '-')}`,
    version: '0.0.1',
    private: true,
    type: 'module',
    scripts: {
      start: 'npx tsx runtime.ts',
    },
    dependencies: deps,
    devDependencies: {
      tsx: '^4.0.0',
      typescript: '^5.7.0',
    },
  };
}

// ─── Config Generation ──────────────────────────────────────────────────────

/**
 * Generate a `config.json` with resolved agent, model, tool, and MCP
 * configuration extracted from the assembly.
 *
 * This file is informational and can be used by the runtime for
 * dynamic configuration or debugging.
 *
 * @param assembly - The Agent Assembly.
 * @returns A plain object suitable for JSON serialization.
 */
export function generateConfigJson(assembly: AgentAssembly): Record<string, unknown> {
  const agents = findResources(assembly, 'agentforge::core::Agent');
  const models = findResources(assembly, 'agentforge::core::Model');
  const tools = findResources(assembly, 'agentforge::core::Tool');
  const prompts = findResources(assembly, 'agentforge::core::Prompt');
  const mcpServers = findResources(assembly, 'agentforge::core::MCPServer');

  return {
    generatedAt: new Date().toISOString(),
    assemblyVersion: assembly.version,
    stackName: assembly.metadata.stackName,
    agents: agents.map(a => ({
      id: a.id,
      name: a.displayName,
      properties: a.properties,
    })),
    models: models.map(m => ({
      id: m.id,
      name: m.displayName,
      properties: m.properties,
    })),
    tools: tools.map(t => ({
      id: t.id,
      name: t.displayName,
      properties: t.properties,
    })),
    prompts: prompts.map(p => ({
      id: p.id,
      name: p.displayName,
      properties: p.properties,
    })),
    mcpServers: mcpServers.map(s => ({
      id: s.id,
      name: s.displayName,
      properties: s.properties,
    })),
    connections: assembly.connections,
  };
}
