/**
 * @module protocols
 *
 * Protocol artifact generators.
 *
 * AgentForge generates protocol artifacts from agent definitions as part of
 * the build process. This module provides generators for:
 *
 * - **AGENTS.md** — The OpenAI-originated standard for agent discovery (Phase 1)
 * - **A2A Agent Card** — Google's Agent-to-Agent protocol card (Phase 2 stub)
 * - **Agent Skills Manifest** — Anthropic's skills format (Phase 2 stub)
 *
 * @see Section 2.11 of the AgentForge roadmap.
 */

import type { AgentResource } from './assembly.js';

// ─── AGENTS.md Generator ────────────────────────────────────────────────────

/**
 * Generate an AGENTS.md file from agent resources.
 *
 * Produces a Markdown document following the AGENTS.md convention
 * (originated by OpenAI, adopted by 60K+ repos). The document lists
 * all agents with their descriptions, models, tools, and guardrails.
 *
 * @param resources - All resources in the assembly, keyed by construct path.
 * @returns The AGENTS.md content as a string.
 *
 * @example Output:
 * ```markdown
 * # AGENTS.md
 * # Generated by AgentForge — do not edit manually
 *
 * ## researcher
 * - **Description:** Research assistant
 * - **Model:** anthropic/claude-sonnet-4
 * - **Tools:** web_search, file_read
 * - **Guardrails:** pii_redaction
 * ```
 */
export function generateAgentsMd(
  resources: Record<string, AgentResource>,
): string {
  const lines: string[] = [
    '# AGENTS.md',
    '# Generated by AgentForge — do not edit manually',
    '',
  ];

  // Find all agent resources
  const agents = Object.values(resources).filter(
    (r) => r.type === 'agentforge::core::Agent',
  );

  if (agents.length === 0) {
    lines.push('_No agents defined._');
    return lines.join('\n');
  }

  for (const agent of agents) {
    const name = (agent.properties['name'] as string) ?? agent.displayName;
    const description = agent.properties['description'] as string | undefined;

    lines.push(`## ${name}`);

    if (description) {
      lines.push(`- **Description:** ${description}`);
    }

    // Find bound model
    const modelId = resolveModelDisplay(agent, resources);
    if (modelId) {
      lines.push(`- **Model:** ${modelId}`);
    }

    // Find bound tools
    const tools = resolveToolNames(agent, resources);
    if (tools.length > 0) {
      lines.push(`- **Tools:** ${tools.join(', ')}`);
    }

    // Find bound guardrails
    const guardrails = resolveGuardrailNames(agent, resources);
    if (guardrails.length > 0) {
      lines.push(`- **Guardrails:** ${guardrails.join(', ')}`);
    }

    lines.push('');
  }

  return lines.join('\n');
}

// ─── A2A Agent Card Generator (Phase 2 stub) ───────────────────────────────

/**
 * A2A Agent Card structure.
 */
export interface A2AAgentCard {
  readonly name: string;
  readonly description: string;
  readonly url?: string;
  readonly version: string;
  readonly capabilities: {
    readonly streaming: boolean;
    readonly pushNotifications: boolean;
  };
  readonly skills: Array<{
    readonly id: string;
    readonly name: string;
    readonly description: string;
  }>;
  readonly authentication?: {
    readonly schemes: string[];
  };
}

/**
 * Generate an A2A Agent Card JSON from agent resources.
 *
 * **Phase 2 stub** — returns a basic card structure. Full implementation
 * will extract capabilities, skills, and authentication from the assembly.
 *
 * @param resources - All resources in the assembly.
 * @returns The A2A Agent Card as a JSON string, or `null` if no agents found.
 */
export function generateA2AAgentCard(
  resources: Record<string, AgentResource>,
): string | null {
  const agents = Object.values(resources).filter(
    (r) => r.type === 'agentforge::core::Agent',
  );

  if (agents.length === 0) {
    return null;
  }

  // Use the first agent for the card (multi-agent cards TBD in Phase 2)
  const agent = agents[0]!;
  const name = (agent.properties['name'] as string) ?? agent.displayName;
  const description = (agent.properties['description'] as string) ?? '';

  const tools = resolveToolNames(agent, resources);

  const card: A2AAgentCard = {
    name,
    description,
    version: '1.0.0',
    capabilities: {
      streaming: false,
      pushNotifications: false,
    },
    skills: tools.map((toolName) => ({
      id: toolName,
      name: toolName,
      description: `Tool: ${toolName}`,
    })),
  };

  return JSON.stringify(card, null, 2);
}

// ─── Agent Skills Manifest Generator (Phase 2 stub) ─────────────────────────

/**
 * Agent Skills manifest structure.
 */
export interface AgentSkillsManifest {
  readonly schema_version: string;
  readonly name_for_human: string;
  readonly name_for_model: string;
  readonly description_for_human: string;
  readonly description_for_model: string;
  readonly skills: Array<{
    readonly name: string;
    readonly description: string;
    readonly parameters?: Record<string, unknown>;
  }>;
}

/**
 * Generate an Agent Skills manifest JSON from agent resources.
 *
 * **Phase 2 stub** — returns a basic manifest structure. Full implementation
 * will extract input schemas and detailed skill descriptions from the assembly.
 *
 * @param resources - All resources in the assembly.
 * @returns The Agent Skills manifest as a JSON string, or `null` if no agents found.
 */
export function generateAgentSkillsManifest(
  resources: Record<string, AgentResource>,
): string | null {
  const agents = Object.values(resources).filter(
    (r) => r.type === 'agentforge::core::Agent',
  );

  if (agents.length === 0) {
    return null;
  }

  const agent = agents[0]!;
  const name = (agent.properties['name'] as string) ?? agent.displayName;
  const description = (agent.properties['description'] as string) ?? '';

  const tools = resolveToolNames(agent, resources);

  const manifest: AgentSkillsManifest = {
    schema_version: '1.0',
    name_for_human: name,
    name_for_model: name.toLowerCase().replace(/\s+/g, '_'),
    description_for_human: description,
    description_for_model: description,
    skills: tools.map((toolName) => ({
      name: toolName,
      description: `Tool: ${toolName}`,
    })),
  };

  return JSON.stringify(manifest, null, 2);
}

// ─── Internal Helpers ───────────────────────────────────────────────────────

/**
 * Resolve the display string for an agent's model.
 */
function resolveModelDisplay(
  agent: AgentResource,
  resources: Record<string, AgentResource>,
): string | undefined {
  // Check direct model property
  const modelProp = agent.properties['model'];
  if (typeof modelProp === 'string') {
    return modelProp;
  }

  // Look for model_binding connections or model dependency
  for (const depId of agent.dependencies) {
    const dep = resources[depId];
    if (dep && dep.type === 'agentforge::core::Model') {
      const provider = dep.properties['provider'] as string | undefined;
      const modelId = dep.properties['modelId'] as string | undefined;
      if (provider && modelId) {
        return `${provider}/${modelId}`;
      }
      return modelId ?? dep.displayName;
    }
  }

  return undefined;
}

/**
 * Resolve tool names bound to an agent.
 */
function resolveToolNames(
  agent: AgentResource,
  resources: Record<string, AgentResource>,
): string[] {
  const names: string[] = [];

  // Check tools array in properties
  const toolsProp = agent.properties['tools'];
  if (Array.isArray(toolsProp)) {
    for (const t of toolsProp) {
      if (typeof t === 'string') {
        names.push(t);
      } else if (typeof t === 'object' && t !== null && 'name' in t) {
        names.push((t as { name: string }).name);
      }
    }
  }

  // Also check dependencies for Tool resources
  for (const depId of agent.dependencies) {
    const dep = resources[depId];
    if (dep && dep.type === 'agentforge::core::Tool') {
      const toolName = (dep.properties['name'] as string) ?? dep.displayName;
      if (!names.includes(toolName)) {
        names.push(toolName);
      }
    }
  }

  return names;
}

/**
 * Resolve guardrail names bound to an agent.
 */
function resolveGuardrailNames(
  agent: AgentResource,
  resources: Record<string, AgentResource>,
): string[] {
  const names: string[] = [];

  for (const depId of agent.dependencies) {
    const dep = resources[depId];
    if (dep && dep.type === 'agentforge::governance::Guardrail') {
      const name = (dep.properties['name'] as string) ?? dep.displayName;
      names.push(name);
    }
  }

  return names;
}
